#!/usr/bin/env python3
"""Regenerates crates/sim-core/src/yaw_lut.rs.

sim-core bans libm/trig at runtime (CLAUDE.md wall 1); yaw -> direction goes
through a fixed 256-entry table indexed by the high byte of the wire yaw u16
(DESIGN.md par.4). The table is authored here, offline, and committed as f32
bit patterns so the constants are exact on every target by construction.

Convention: index 0 faces +Z; increasing index rotates toward +X (clockwise
seen from above, +Y up). dx = sin(theta), dz = cos(theta), theta = i/256 * 2pi.
"""

import math
import struct

def f32_bits(x: float) -> int:
    return struct.unpack("<I", struct.pack("<f", x))[0]

rows = []
for i in range(256):
    theta = 2.0 * math.pi * i / 256.0
    dx, dz = math.sin(theta), math.cos(theta)
    rows.append(f"    [0x{f32_bits(dx):08X}, 0x{f32_bits(dz):08X}], // {i:3d}")

out = f"""//! Yaw -> unit direction, 256 entries. GENERATED by ci/gen_yaw_lut.py — do
//! not edit by hand; regenerate and commit both files together.
//!
//! sim-core may not call trig at runtime (CLAUDE.md wall 1), so the shared
//! yaw table is authored offline and stored as f32 bit patterns: exact and
//! bit-identical native/wasm by construction. Index = wire yaw u16 >> 8.
//! Index 0 faces +Z; increasing index rotates toward +X. [dx_bits, dz_bits].

const YAW_LUT_BITS: [[u32; 2]; 256] = [
{chr(10).join(rows)}
];

/// Unit (dx, dz) for a wire yaw. Uses only the table + from_bits: exact.
#[inline]
pub fn yaw_dir(yaw: u16) -> (f32, f32) {{
    let e = YAW_LUT_BITS[(yaw >> 8) as usize];
    (f32::from_bits(e[0]), f32::from_bits(e[1]))
}}
"""

with open("crates/sim-core/src/yaw_lut.rs", "w") as f:
    f.write(out)
print("wrote crates/sim-core/src/yaw_lut.rs")
