#!/usr/bin/env python3
"""Regenerates crates/sim-core/src/pitch_lut.rs.

Sibling of ci/gen_yaw_lut.py, and for the same reason: sim-core bans
libm/trig at runtime (CLAUDE.md wall 1), so an angle -> direction table is
authored here, offline, and committed as f32 bit patterns.

Convention comes from the client, which has been sending this byte since
before anything read it (web/src/input.js `pitchU8`):

    u8 = round((rad / pi + 0.5) * 255)        rad in [-pi/2, +pi/2], + is up

so the inverse this table bakes is rad = (u/255 - 0.5) * pi. Entry 0 is
straight down, 255 is straight up, and level falls between 127 and 128 --
there is no exact integer for level, which is a property of the client's
encoding and not something this table may round away.

Unlike the yaw table this one is NOT circular: index 255 does not wrap to
index 0, it is the opposite pole. Nothing here may take a yaw table's
mod-256 shortcut.

Each row is [cos_bits, sin_bits]: cos scales the planar (yaw) direction,
sin is the vertical component.
"""

import math
import struct


def f32_bits(x):
    """The IEEE-754 bit pattern of x rounded to f32 -- exact on every target."""
    return struct.unpack("<I", struct.pack("<f", x))[0]


rows = []
for i in range(256):
    theta = (i / 255.0 - 0.5) * math.pi
    ch, sv = math.cos(theta), math.sin(theta)
    rows.append(f"    [0x{f32_bits(ch):08X}, 0x{f32_bits(sv):08X}], // {i:3d}")

out = f"""//! Pitch -> vertical direction, 256 entries. GENERATED by
//! ci/gen_pitch_lut.py — do not edit by hand; regenerate and commit both
//! files together.
//!
//! sim-core may not call trig at runtime (CLAUDE.md wall 1), so this table
//! is authored offline and stored as f32 bit patterns: exact and
//! bit-identical native/wasm by construction, exactly like `yaw_lut`.
//!
//! The encoding is the client's, unchanged since before the sim read it
//! (`web/src/input.js` pitchU8): `u8 = round((rad/pi + 0.5) * 255)` over
//! [-pi/2, +pi/2] with + up, so index 0 is straight down, 255 straight up,
//! and level lands between 127 and 128. Every one of the 256 values is
//! wire-legal (the decoder range-checks `sel`, never `pitch`), so this
//! table is indexed by the raw byte and cannot be short.
//!
//! NOT circular, unlike the yaw table: 255 is the opposite pole from 0, not
//! its neighbour. [cos_bits, sin_bits] — cos scales the planar direction,
//! sin is the vertical component.

const PITCH_LUT_BITS: [[u32; 2]; 256] = [
{chr(10).join(rows)}
];

/// Planar scale and vertical component for a wire pitch. Uses only the
/// table + from_bits: exact.
#[inline]
pub fn pitch_dir(pitch: u8) -> (f32, f32) {{
    let e = PITCH_LUT_BITS[pitch as usize];
    (f32::from_bits(e[0]), f32::from_bits(e[1]))
}}
"""

with open("crates/sim-core/src/pitch_lut.rs", "w") as f:
    f.write(out)
print("wrote crates/sim-core/src/pitch_lut.rs")
