//! Pitch -> vertical direction, 256 entries. GENERATED by
//! ci/gen_pitch_lut.py — do not edit by hand; regenerate and commit both
//! files together.
//!
//! sim-core may not call trig at runtime (CLAUDE.md wall 1), so this table
//! is authored offline and stored as f32 bit patterns: exact and
//! bit-identical native/wasm by construction, exactly like `yaw_lut`.
//!
//! The encoding is the client's, unchanged since before the sim read it
//! (`web/src/input.js` pitchU8): `u8 = round((rad/pi + 0.5) * 255)` over
//! [-pi/2, +pi/2] with + up, so index 0 is straight down, 255 straight up,
//! and level lands between 127 and 128. Every one of the 256 values is
//! wire-legal (the decoder range-checks `sel`, never `pitch`), so this
//! table is indexed by the raw byte and cannot be short.
//!
//! NOT circular, unlike the yaw table: 255 is the opposite pole from 0, not
//! its neighbour. [cos_bits, sin_bits] — cos scales the planar direction,
//! sin is the vertical component.

const PITCH_LUT_BITS: [[u32; 2]; 256] = [
    [0x248D3132, 0xBF800000], //   0
    [0x3C49D866, 0xBF7FFB07], //   1
    [0x3CC9D47A, 0xBF7FEC1B], //   2
    [0x3D175A75, 0xBF7FD33E], //   3
    [0x3D49C4CB, 0xBF7FB070], //   4
    [0x3D7C274A, 0xBF7F83B3], //   5
    [0x3D973FFE, 0xBF7F4D08], //   6
    [0x3DB06677, 0xBF7F0C72], //   7
    [0x3DC98616, 0xBF7EC1F3], //   8
    [0x3DE29DE0, 0xBF7E6D8D], //   9
    [0x3DFBACDB, 0xBF7E0F45], //  10
    [0x3E0A5908, 0xBF7DA71E], //  11
    [0x3E16D642, 0xBF7D351C], //  12
    [0x3E234D9F, 0xBF7CB942], //  13
    [0x3E2FBEA4, 0xBF7C3398], //  14
    [0x3E3C28D5, 0xBF7BA420], //  15
    [0x3E488BB7, 0xBF7B0AE1], //  16
    [0x3E54E6CD, 0xBF7A67E2], //  17
    [0x3E61399E, 0xBF79BB27], //  18
    [0x3E6D83AF, 0xBF7904B8], //  19
    [0x3E79C485, 0xBF78449D], //  20
    [0x3E82FDD3, 0xBF777ADB], //  21
    [0x3E89144D, 0xBF76A77D], //  22
    [0x3E8F2573, 0xBF75CA88], //  23
    [0x3E953109, 0xBF74E407], //  24
    [0x3E9B36D4, 0xBF73F402], //  25
    [0x3EA13696, 0xBF72FA82], //  26
    [0x3EA73015, 0xBF71F791], //  27
    [0x3EAD2315, 0xBF70EB3A], //  28
    [0x3EB30F5A, 0xBF6FD586], //  29
    [0x3EB8F4AB, 0xBF6EB680], //  30
    [0x3EBED2CC, 0xBF6D8E34], //  31
    [0x3EC4A982, 0xBF6C5CAD], //  32
    [0x3ECA7895, 0xBF6B21F7], //  33
    [0x3ED03FC9, 0xBF69DE1D], //  34
    [0x3ED5FEE6, 0xBF68912E], //  35
    [0x3EDBB5B2, 0xBF673B35], //  36
    [0x3EE163F5, 0xBF65DC41], //  37
    [0x3EE70976, 0xBF64745D], //  38
    [0x3EECA5FD, 0xBF63039A], //  39
    [0x3EF23952, 0xBF618A04], //  40
    [0x3EF7C33D, 0xBF6007AB], //  41
    [0x3EFD4388, 0xBF5E7C9D], //  42
    [0x3F015CFE, 0xBF5CE8EA], //  43
    [0x3F041331, 0xBF5B4CA2], //  44
    [0x3F06C442, 0xBF59A7D5], //  45
    [0x3F097017, 0xBF57FA92], //  46
    [0x3F0C1695, 0xBF5644EB], //  47
    [0x3F0EB7A1, 0xBF5486F1], //  48
    [0x3F115321, 0xBF52C0B5], //  49
    [0x3F13E8FC, 0xBF50F248], //  50
    [0x3F167918, 0xBF4F1BBD], //  51
    [0x3F19035B, 0xBF4D3D26], //  52
    [0x3F1B87AC, 0xBF4B5695], //  53
    [0x3F1E05F2, 0xBF49681E], //  54
    [0x3F207E14, 0xBF4771D3], //  55
    [0x3F22EFFA, 0xBF4573C9], //  56
    [0x3F255B8B, 0xBF436E12], //  57
    [0x3F27C0AF, 0xBF4160C3], //  58
    [0x3F2A1F4E, 0xBF3F4BF1], //  59
    [0x3F2C7751, 0xBF3D2FB0], //  60
    [0x3F2EC8A1, 0xBF3B0C15], //  61
    [0x3F311326, 0xBF38E136], //  62
    [0x3F3356CA, 0xBF36AF28], //  63
    [0x3F359376, 0xBF347600], //  64
    [0x3F37C913, 0xBF3235D6], //  65
    [0x3F39F78D, 0xBF2FEEBE], //  66
    [0x3F3C1ECD, 0xBF2DA0D1], //  67
    [0x3F3E3EBD, 0xBF2B4C25], //  68
    [0x3F405749, 0xBF28F0D0], //  69
    [0x3F42685C, 0xBF268EEC], //  70
    [0x3F4471E1, 0xBF24268E], //  71
    [0x3F4673C5, 0xBF21B7D0], //  72
    [0x3F486DF2, 0xBF1F42C9], //  73
    [0x3F4A6055, 0xBF1CC792], //  74
    [0x3F4C4ADB, 0xBF1A4643], //  75
    [0x3F4E2D72, 0xBF17BEF6], //  76
    [0x3F500805, 0xBF1531C4], //  77
    [0x3F51DA83, 0xBF129EC5], //  78
    [0x3F53A4DA, 0xBF100614], //  79
    [0x3F5566F7, 0xBF0D67CA], //  80
    [0x3F5720CA, 0xBF0AC402], //  81
    [0x3F58D241, 0xBF081AD6], //  82
    [0x3F5A7B4B, 0xBF056C5F], //  83
    [0x3F5C1BD8, 0xBF02B8BA], //  84
    [0x3F5DB3D7, 0xBF000000], //  85
    [0x3F5F4339, 0xBEFA849A], //  86
    [0x3F60C9EF, 0xBEF4FF78], //  87
    [0x3F6247E8, 0xBEEF70D1], //  88
    [0x3F63BD17, 0xBEE9D8DC], //  89
    [0x3F65296C, 0xBEE437D1], //  90
    [0x3F668CDA, 0xBEDE8DE8], //  91
    [0x3F67E752, 0xBED8DB5A], //  92
    [0x3F6938C8, 0xBED3205E], //  93
    [0x3F6A812E, 0xBECD5D2E], //  94
    [0x3F6BC077, 0xBEC79204], //  95
    [0x3F6CF697, 0xBEC1BF18], //  96
    [0x3F6E2382, 0xBEBBE4A5], //  97
    [0x3F6F472C, 0xBEB602E5], //  98
    [0x3F70618B, 0xBEB01A13], //  99
    [0x3F717292, 0xBEAA2A69], // 100
    [0x3F727A37, 0xBEA43422], // 101
    [0x3F737871, 0xBE9E377A], // 102
    [0x3F746D34, 0xBE9834AC], // 103
    [0x3F755879, 0xBE922BF4], // 104
    [0x3F763A35, 0xBE8C1D8E], // 105
    [0x3F77125F, 0xBE8609B7], // 106
    [0x3F77E0F0, 0xBE7FE154], // 107
    [0x3F78A5E0, 0xBE73A549], // 108
    [0x3F796126, 0xBE675FC6], // 109
    [0x3F7A12BB, 0xBE5B1146], // 110
    [0x3F7ABA99, 0xBE4EBA43], // 111
    [0x3F7B58B9, 0xBE425B38], // 112
    [0x3F7BED15, 0xBE35F49F], // 113
    [0x3F7C77A7, 0xBE2986F5], // 114
    [0x3F7CF86A, 0xBE1D12B4], // 115
    [0x3F7D6F58, 0xBE109858], // 116
    [0x3F7DDC6D, 0xBE04185F], // 117
    [0x3F7E3FA5, 0xBDEF2687], // 118
    [0x3F7E98FD, 0xBDD61305], // 119
    [0x3F7EE86F, 0xBDBCF732], // 120
    [0x3F7F2DFA, 0xBDA3D407], // 121
    [0x3F7F699B, 0xBD8AAA7E], // 122
    [0x3F7F9B50, 0xBD62F725], // 123
    [0x3F7FC315, 0xBD30907B], // 124
    [0x3F7FE0EB, 0xBCFC45EB], // 125
    [0x3F7FF4CF, 0xBC976113], // 126
    [0x3F7FFEC2, 0xBBC9D961], // 127
    [0x3F7FFEC2, 0x3BC9D961], // 128
    [0x3F7FF4CF, 0x3C976113], // 129
    [0x3F7FE0EB, 0x3CFC45EB], // 130
    [0x3F7FC315, 0x3D30907B], // 131
    [0x3F7F9B50, 0x3D62F725], // 132
    [0x3F7F699B, 0x3D8AAA7E], // 133
    [0x3F7F2DFA, 0x3DA3D407], // 134
    [0x3F7EE86F, 0x3DBCF732], // 135
    [0x3F7E98FD, 0x3DD61305], // 136
    [0x3F7E3FA5, 0x3DEF2687], // 137
    [0x3F7DDC6D, 0x3E04185F], // 138
    [0x3F7D6F58, 0x3E109858], // 139
    [0x3F7CF86A, 0x3E1D12B4], // 140
    [0x3F7C77A7, 0x3E2986F5], // 141
    [0x3F7BED15, 0x3E35F49F], // 142
    [0x3F7B58B9, 0x3E425B38], // 143
    [0x3F7ABA99, 0x3E4EBA43], // 144
    [0x3F7A12BB, 0x3E5B1146], // 145
    [0x3F796126, 0x3E675FC6], // 146
    [0x3F78A5E0, 0x3E73A549], // 147
    [0x3F77E0F0, 0x3E7FE154], // 148
    [0x3F77125F, 0x3E8609B7], // 149
    [0x3F763A35, 0x3E8C1D8E], // 150
    [0x3F755879, 0x3E922BF4], // 151
    [0x3F746D34, 0x3E9834AC], // 152
    [0x3F737871, 0x3E9E377A], // 153
    [0x3F727A37, 0x3EA43422], // 154
    [0x3F717292, 0x3EAA2A69], // 155
    [0x3F70618B, 0x3EB01A13], // 156
    [0x3F6F472C, 0x3EB602E5], // 157
    [0x3F6E2382, 0x3EBBE4A5], // 158
    [0x3F6CF697, 0x3EC1BF18], // 159
    [0x3F6BC077, 0x3EC79204], // 160
    [0x3F6A812E, 0x3ECD5D2E], // 161
    [0x3F6938C8, 0x3ED3205E], // 162
    [0x3F67E752, 0x3ED8DB5A], // 163
    [0x3F668CDA, 0x3EDE8DE8], // 164
    [0x3F65296C, 0x3EE437D1], // 165
    [0x3F63BD17, 0x3EE9D8DC], // 166
    [0x3F6247E8, 0x3EEF70D1], // 167
    [0x3F60C9EF, 0x3EF4FF78], // 168
    [0x3F5F4339, 0x3EFA849A], // 169
    [0x3F5DB3D7, 0x3F000000], // 170
    [0x3F5C1BD8, 0x3F02B8BA], // 171
    [0x3F5A7B4B, 0x3F056C5F], // 172
    [0x3F58D241, 0x3F081AD6], // 173
    [0x3F5720CA, 0x3F0AC402], // 174
    [0x3F5566F7, 0x3F0D67CA], // 175
    [0x3F53A4DA, 0x3F100614], // 176
    [0x3F51DA83, 0x3F129EC5], // 177
    [0x3F500805, 0x3F1531C4], // 178
    [0x3F4E2D72, 0x3F17BEF6], // 179
    [0x3F4C4ADB, 0x3F1A4643], // 180
    [0x3F4A6055, 0x3F1CC792], // 181
    [0x3F486DF2, 0x3F1F42C9], // 182
    [0x3F4673C5, 0x3F21B7D0], // 183
    [0x3F4471E1, 0x3F24268E], // 184
    [0x3F42685C, 0x3F268EEC], // 185
    [0x3F405749, 0x3F28F0D0], // 186
    [0x3F3E3EBD, 0x3F2B4C25], // 187
    [0x3F3C1ECD, 0x3F2DA0D1], // 188
    [0x3F39F78D, 0x3F2FEEBE], // 189
    [0x3F37C913, 0x3F3235D6], // 190
    [0x3F359376, 0x3F347600], // 191
    [0x3F3356CA, 0x3F36AF28], // 192
    [0x3F311326, 0x3F38E136], // 193
    [0x3F2EC8A1, 0x3F3B0C15], // 194
    [0x3F2C7751, 0x3F3D2FB0], // 195
    [0x3F2A1F4E, 0x3F3F4BF1], // 196
    [0x3F27C0AF, 0x3F4160C3], // 197
    [0x3F255B8B, 0x3F436E12], // 198
    [0x3F22EFFA, 0x3F4573C9], // 199
    [0x3F207E14, 0x3F4771D3], // 200
    [0x3F1E05F2, 0x3F49681E], // 201
    [0x3F1B87AC, 0x3F4B5695], // 202
    [0x3F19035B, 0x3F4D3D26], // 203
    [0x3F167918, 0x3F4F1BBD], // 204
    [0x3F13E8FC, 0x3F50F248], // 205
    [0x3F115321, 0x3F52C0B5], // 206
    [0x3F0EB7A1, 0x3F5486F1], // 207
    [0x3F0C1695, 0x3F5644EB], // 208
    [0x3F097017, 0x3F57FA92], // 209
    [0x3F06C442, 0x3F59A7D5], // 210
    [0x3F041331, 0x3F5B4CA2], // 211
    [0x3F015CFE, 0x3F5CE8EA], // 212
    [0x3EFD4388, 0x3F5E7C9D], // 213
    [0x3EF7C33D, 0x3F6007AB], // 214
    [0x3EF23952, 0x3F618A04], // 215
    [0x3EECA5FD, 0x3F63039A], // 216
    [0x3EE70976, 0x3F64745D], // 217
    [0x3EE163F5, 0x3F65DC41], // 218
    [0x3EDBB5B2, 0x3F673B35], // 219
    [0x3ED5FEE6, 0x3F68912E], // 220
    [0x3ED03FC9, 0x3F69DE1D], // 221
    [0x3ECA7895, 0x3F6B21F7], // 222
    [0x3EC4A982, 0x3F6C5CAD], // 223
    [0x3EBED2CC, 0x3F6D8E34], // 224
    [0x3EB8F4AB, 0x3F6EB680], // 225
    [0x3EB30F5A, 0x3F6FD586], // 226
    [0x3EAD2315, 0x3F70EB3A], // 227
    [0x3EA73015, 0x3F71F791], // 228
    [0x3EA13696, 0x3F72FA82], // 229
    [0x3E9B36D4, 0x3F73F402], // 230
    [0x3E953109, 0x3F74E407], // 231
    [0x3E8F2573, 0x3F75CA88], // 232
    [0x3E89144D, 0x3F76A77D], // 233
    [0x3E82FDD3, 0x3F777ADB], // 234
    [0x3E79C485, 0x3F78449D], // 235
    [0x3E6D83AF, 0x3F7904B8], // 236
    [0x3E61399E, 0x3F79BB27], // 237
    [0x3E54E6CD, 0x3F7A67E2], // 238
    [0x3E488BB7, 0x3F7B0AE1], // 239
    [0x3E3C28D5, 0x3F7BA420], // 240
    [0x3E2FBEA4, 0x3F7C3398], // 241
    [0x3E234D9F, 0x3F7CB942], // 242
    [0x3E16D642, 0x3F7D351C], // 243
    [0x3E0A5908, 0x3F7DA71E], // 244
    [0x3DFBACDB, 0x3F7E0F45], // 245
    [0x3DE29DE0, 0x3F7E6D8D], // 246
    [0x3DC98616, 0x3F7EC1F3], // 247
    [0x3DB06677, 0x3F7F0C72], // 248
    [0x3D973FFE, 0x3F7F4D08], // 249
    [0x3D7C274A, 0x3F7F83B3], // 250
    [0x3D49C4CB, 0x3F7FB070], // 251
    [0x3D175A75, 0x3F7FD33E], // 252
    [0x3CC9D47A, 0x3F7FEC1B], // 253
    [0x3C49D866, 0x3F7FFB07], // 254
    [0x248D3132, 0x3F800000], // 255
];

/// Planar scale and vertical component for a wire pitch. Uses only the
/// table + from_bits: exact.
#[inline]
pub fn pitch_dir(pitch: u8) -> (f32, f32) {
    let e = PITCH_LUT_BITS[pitch as usize];
    (f32::from_bits(e[0]), f32::from_bits(e[1]))
}
